name: "📱 Mobile App Feedback / Issue"
description: "Report bugs, crashes, or share improvement ideas for the mobile app"
title: "[Bug/Feedback] <short description here>"
labels: [feedback, needs-triage]
assignees: []

body:
  - type: markdown
    attributes:
      value: "## 📝 Summary\nProvide a clear and concise summary of the issue or feedback."

  - type: input
    id: app_version
    attributes:
      label: App Version
      placeholder: "e.g., 1.3.0"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      multiple: true
      options:
        - Android
        - iOS
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Model
      placeholder: "e.g., iPhone 13, Samsung Galaxy S22"
    validations:
      required: false

  - type: input
    id: os_version
    attributes:
      label: OS Version
      placeholder: "e.g., iOS 16.4, Android 13"
    validations:
      required: false

  - type: checkboxes
    id: issue_type
    attributes:
      label: Issue Type
      options:
        - label: Crash
        - label: UI issue
        - label: Navigation problem
        - label: Performance lag
        - label: Feature not working as expected
        - label: Suggestion / Feedback
        - label: Other (please specify below)

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce (if applicable)
      placeholder: |
        1. Go to '...'
        2. Tap on '...'
        3. Scroll to '...'
        4. See error / issue
    validations:
      required: false

  - type: textarea
    id: expected_vs_actual
    attributes:
      label: Expected vs. Actual Behavior
      placeholder: |
        **Expected:**
        What you expected to happen.

        **Actual:**
        What actually happened.
    validations:
      required: false

  - type: textarea
    id: media
    attributes:
      label: Screenshots / Videos
      placeholder: "You can paste images or video links here"
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional Context or Logs
      placeholder: "Add any other relevant information or error logs here"
    validations:
      required: false
